typedef struct { 
    const char * _fname ;
    const char * _wanted ;
} _STitemX ;

_STitemX _listA1[] = {
{ "01"  , "v down set_wind 1" } ,
{ "02"  , "v down set_wind 1" } ,
{ "03"  , "v down set_wind 1" } ,
{ "04"  , "v down set_wind 1" } ,
{ "05"  , "v down set_wind 1" } ,

{ "06"  , "v down set_wind 0" } ,
{ "07"  , "v down set_wind 0" } ,
{ "08"  , "v down set_wind 0" } ,
{ "09"  , "v down set_wind 0" } ,
{ "10"  , "v down set_wind 0" } ,

{ "11"  , "v down set_wind 1" } ,
{ "12"  , "v down set_wind 1" } ,
{ "13"  , "v down set_wind 1" } ,
{ "14"  , "v down set_wind 1" } ,

{ "15"  , "v down set_wind 16" } ,
{ "17"  , "v down set_wind 16" } ,
{ "19"  , "v down set_wind 16" } ,
{ "20"  , "v down set_wind 4" } ,
{ "21"  , "v down set_wind 4" } ,
{ "22"  , "v down set_wind 4" } ,
{ "23"  , "v down set_wind 4" } ,
{ "24"  , "v down set_wind 4" } ,
{ "25"  , "v down set_wind 4" } ,

{ "26"  , "v down set_light 1" } ,
{ "27"  , "v down set_light 1" } ,
{ "28"  , "v down set_wind 4" } ,
{ "29"  , "v down set_wind 4" } ,
{ "30"  , "v down set_wind 4" } ,
{ "31"  , "v down set_wind 4" } ,
{ "32"  , "v down set_wind 4" } ,
{ "33"  , "v down set_wind 4" } ,
{ "34"  , "v down set_wind 4" } ,
{ "38"  , "v down set_wind 4" } ,
{ "39"  , "v down set_wind 4" } ,
{ "40"  , "v down set_wind 4" } ,
{ "41"  , "v down set_wind 4" } ,
{ "42"  , "v down set_wind 4" } ,
{ "43"  , "v down set_wind 4" } ,
{ "44"  , "v down set_wind 4" } ,
{ "45"  , "v down set_wind 4" } ,
{ "46"  , "v down set_wind 4" } ,
{ "47"  , "v down set_wind 4" } ,
{ "48"  , "v down set_wind 4" } ,
{ "49"  , "v down set_wind 4" } ,
{ "50"  , "v down set_wind 4" } ,
{ "51"  , "v down set_wind 4" } ,
{ "52"  , "v down set_wind 4" } ,
{ "53"  , "v down set_wind 4" } ,
{ "54"  , "v down set_wind 4" } ,
{ "55"  , "v down set_wind 4" } ,
{ "56"  , "v down set_wind 4" } ,
{ "57"  , "v down set_wind 4" } ,
{ "58"  , "v down set_wind 4" } ,
{ "59"  , "v down set_wind 4" } ,
{ "60"  , "v down set_wind 4" } ,
{ "61"  , "v down set_wind 4" } ,
{ "62"  , "v down set_wind 4" } ,
{ "63"  , "v down set_wind 4" } ,
{ "64"  , "v down set_wind 4" } ,
{ "65"  , "v down set_wind 4" } ,
{ "66"  , "v down set_wind 4" } ,
{ "67"  , "v down set_wind 4" } ,
{ "68"  , "v down set_wind 4" } ,
{ "69"  , "v down set_wind 4" } ,
{ "70"  , "v down set_wind 4" } ,
{ "71"  , "v down set_wind 4" } ,
{ "72"  , "v down set_wind 4" } ,
{ "73"  , "v down set_wind 4" } ,
{ "74"  , "v down set_wind 4" } ,
{ "75"  , "v down set_wind 4" } ,
{ "76"  , "v down set_wind 4" } ,
{ "77"  , "v down set_wind 4" } ,
{ "78"  , "v down set_wind 4" } ,
{ "79"  , "v down set_wind 4" } ,
{ "80"  , "v down set_wind 4" } ,
{ "81"  , "v down set_wind 4" } ,
{ "88"  , "v down set_wind 4" } ,
{ "89"  , "v down set_wind 4" } 
};
